# Generated by Django 4.2.11 on 2026-02-02 12:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_leads', models.IntegerField(default=0)),
                ('new_leads_this_month', models.IntegerField(default=0)),
                ('active_deals', models.IntegerField(default=0)),
                ('deals_in_progress', models.IntegerField(default=0)),
                ('won_deals_total', models.IntegerField(default=0)),
                ('lost_deals_total', models.IntegerField(default=0)),
                ('total_deal_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('customer_satisfaction_rate', models.FloatField(default=0, help_text='Percentage of won deals')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_metric', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Metric',
                'verbose_name_plural': 'Dashboard Metrics',
            },
        ),
        migrations.CreateModel(
            name='MarketingPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField()),
                ('total_hours', models.FloatField(default=0, help_text='Total hours worked')),
                ('active_hours', models.FloatField(default=0, help_text='Hours spent on active tasks')),
                ('leads_contacted', models.IntegerField(default=0)),
                ('deals_progressed', models.IntegerField(default=0)),
                ('calls_made', models.IntegerField(default=0)),
                ('meetings_held', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0, help_text='Percentage')),
                ('avg_deal_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-metric_date'],
                'unique_together': {('user', 'metric_date')},
            },
        ),
        migrations.CreateModel(
            name='DashboardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('lead_created', 'Lead Created'), ('lead_updated', 'Lead Updated'), ('lead_deleted', 'Lead Deleted'), ('deal_created', 'Deal Created'), ('deal_updated', 'Deal Updated'), ('deal_stage_changed', 'Deal Stage Changed'), ('deal_won', 'Deal Won'), ('deal_lost', 'Deal Lost'), ('task_created', 'Task Created'), ('task_completed', 'Task Completed'), ('comment_added', 'Comment Added'), ('file_uploaded', 'File Uploaded'), ('team_joined', 'Team Member Joined')], max_length=30)),
                ('lead_id', models.IntegerField(blank=True, null=True)),
                ('deal_id', models.IntegerField(blank=True, null=True)),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(help_text="e.g., 'Acme Corp Lead Created'", max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('action', models.CharField(help_text="e.g., 'Lead created for Acme Corp'", max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dashboard_d_user_id_b651a6_idx'), models.Index(fields=['activity_type', '-created_at'], name='dashboard_d_activit_722346_idx')],
            },
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('follow_up', 'Follow-up Needed'), ('risk_alert', 'Lead at Risk'), ('opportunity', 'Opportunity'), ('performance', 'Performance Insight'), ('close_date', 'Close Date Warning')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(help_text="e.g., '3 leads at risk'", max_length=255)),
                ('description', models.TextField(help_text='Detailed explanation and recommendation')),
                ('confidence_score', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('lead_ids', models.TextField(blank=True, help_text='Comma-separated lead IDs', null=True)),
                ('deal_ids', models.TextField(blank=True, help_text='Comma-separated deal IDs', null=True)),
                ('metric_value', models.CharField(blank=True, max_length=100, null=True)),
                ('metric_change', models.CharField(blank=True, help_text="e.g., '+15%' or '-5%'", max_length=100, null=True)),
                ('is_actioned', models.BooleanField(default=False)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('action_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this suggestion becomes outdated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dashboard_a_user_id_d0e61e_idx'), models.Index(fields=['priority', '-created_at'], name='dashboard_a_priorit_c4f5bc_idx')],
            },
        ),
    ]
